// automatically generated by the FlatBuffers compiler, do not modify

package dafi.flatbuf;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class AttribColumn extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_25_2_10(); }
  public static AttribColumn getRootAsAttribColumn(ByteBuffer _bb) { return getRootAsAttribColumn(_bb, new AttribColumn()); }
  public static AttribColumn getRootAsAttribColumn(ByteBuffer _bb, AttribColumn obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public AttribColumn __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int attrib() { int o = __offset(4); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public byte contentsType() { int o = __offset(6); return o != 0 ? bb.get(o + bb_pos) : 0; }
  public Table contents(Table obj) { int o = __offset(8); return o != 0 ? __union(obj, o + bb_pos) : null; }

  public static int createAttribColumn(FlatBufferBuilder builder,
      int attrib,
      byte contentsType,
      int contentsOffset) {
    builder.startTable(3);
    AttribColumn.addContents(builder, contentsOffset);
    AttribColumn.addAttrib(builder, attrib);
    AttribColumn.addContentsType(builder, contentsType);
    return AttribColumn.endAttribColumn(builder);
  }

  public static void startAttribColumn(FlatBufferBuilder builder) { builder.startTable(3); }
  public static void addAttrib(FlatBufferBuilder builder, int attrib) { builder.addInt(0, attrib, 0); }
  public static void addContentsType(FlatBufferBuilder builder, byte contentsType) { builder.addByte(1, contentsType, 0); }
  public static void addContents(FlatBufferBuilder builder, int contentsOffset) { builder.addOffset(2, contentsOffset, 0); }
  public static int endAttribColumn(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public AttribColumn get(int j) { return get(new AttribColumn(), j); }
    public AttribColumn get(AttribColumn obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

