// automatically generated by the FlatBuffers compiler, do not modify

package dafi.flatbuf;

@SuppressWarnings("unused")
public final class BundleSectionContents {
  private BundleSectionContents() { }
  public static final byte NONE = 0;
  public static final byte manifest = 1;

  public static final String[] names = { "NONE", "manifest", };

  public static String name(int e) { return names[e]; }
}

