// automatically generated by the FlatBuffers compiler, do not modify

package dafi.flatbuf;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class BundleSection extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_25_2_10(); }
  public static BundleSection getRootAsBundleSection(ByteBuffer _bb) { return getRootAsBundleSection(_bb, new BundleSection()); }
  public static BundleSection getRootAsBundleSection(ByteBuffer _bb, BundleSection obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public static boolean BundleSectionBufferHasIdentifier(ByteBuffer _bb) { return __has_identifier(_bb, "CTFS"); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public BundleSection __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public byte contentsType() { int o = __offset(4); return o != 0 ? bb.get(o + bb_pos) : 0; }
  public Table contents(Table obj) { int o = __offset(6); return o != 0 ? __union(obj, o + bb_pos) : null; }

  public static int createBundleSection(FlatBufferBuilder builder,
      byte contentsType,
      int contentsOffset) {
    builder.startTable(2);
    BundleSection.addContents(builder, contentsOffset);
    BundleSection.addContentsType(builder, contentsType);
    return BundleSection.endBundleSection(builder);
  }

  public static void startBundleSection(FlatBufferBuilder builder) { builder.startTable(2); }
  public static void addContentsType(FlatBufferBuilder builder, byte contentsType) { builder.addByte(0, contentsType, 0); }
  public static void addContents(FlatBufferBuilder builder, int contentsOffset) { builder.addOffset(1, contentsOffset, 0); }
  public static int endBundleSection(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }
  public static void finishBundleSectionBuffer(FlatBufferBuilder builder, int offset) { builder.finish(offset, "CTFS"); }
  public static void finishSizePrefixedBundleSectionBuffer(FlatBufferBuilder builder, int offset) { builder.finishSizePrefixed(offset, "CTFS"); }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public BundleSection get(int j) { return get(new BundleSection(), j); }
    public BundleSection get(BundleSection obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

