// automatically generated by the FlatBuffers compiler, do not modify

package dafi.flatbuf;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class BundleManifest extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_25_2_10(); }
  public static BundleManifest getRootAsBundleManifest(ByteBuffer _bb) { return getRootAsBundleManifest(_bb, new BundleManifest()); }
  public static BundleManifest getRootAsBundleManifest(ByteBuffer _bb, BundleManifest obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public BundleManifest __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public dafi.flatbuf.BundleDescription description() { return description(new dafi.flatbuf.BundleDescription()); }
  public dafi.flatbuf.BundleDescription description(dafi.flatbuf.BundleDescription obj) { int o = __offset(4); return o != 0 ? obj.__assign(__indirect(o + bb_pos), bb) : null; }

  public static int createBundleManifest(FlatBufferBuilder builder,
      int descriptionOffset) {
    builder.startTable(1);
    BundleManifest.addDescription(builder, descriptionOffset);
    return BundleManifest.endBundleManifest(builder);
  }

  public static void startBundleManifest(FlatBufferBuilder builder) { builder.startTable(1); }
  public static void addDescription(FlatBufferBuilder builder, int descriptionOffset) { builder.addOffset(0, descriptionOffset, 0); }
  public static int endBundleManifest(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public BundleManifest get(int j) { return get(new BundleManifest(), j); }
    public BundleManifest get(BundleManifest obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

