// automatically generated by the FlatBuffers compiler, do not modify

package dafi.flatbuf;

@SuppressWarnings("unused")
public final class ColumnContents {
  private ColumnContents() { }
  public static final byte NONE = 0;
  public static final byte LongArrayColumn = 1;
  public static final byte StringArrayColumn = 2;

  public static final String[] names = { "NONE", "LongArrayColumn", "StringArrayColumn", };

  public static String name(int e) { return names[e]; }
}

