// automatically generated by the FlatBuffers compiler, do not modify

package dafi.flatbuf;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class EntitySetDescription extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_25_2_10(); }
  public static EntitySetDescription getRootAsEntitySetDescription(ByteBuffer _bb) { return getRootAsEntitySetDescription(_bb, new EntitySetDescription()); }
  public static EntitySetDescription getRootAsEntitySetDescription(ByteBuffer _bb, EntitySetDescription obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public EntitySetDescription __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public byte type() { int o = __offset(4); return o != 0 ? bb.get(o + bb_pos) : 0; }
  public dafi.flatbuf.EntityPackageDescription packages(int j) { return packages(new dafi.flatbuf.EntityPackageDescription(), j); }
  public dafi.flatbuf.EntityPackageDescription packages(dafi.flatbuf.EntityPackageDescription obj, int j) { int o = __offset(6); return o != 0 ? obj.__assign(__indirect(__vector(o) + j * 4), bb) : null; }
  public int packagesLength() { int o = __offset(6); return o != 0 ? __vector_len(o) : 0; }
  public dafi.flatbuf.EntityPackageDescription.Vector packagesVector() { return packagesVector(new dafi.flatbuf.EntityPackageDescription.Vector()); }
  public dafi.flatbuf.EntityPackageDescription.Vector packagesVector(dafi.flatbuf.EntityPackageDescription.Vector obj) { int o = __offset(6); return o != 0 ? obj.__assign(__vector(o), 4, bb) : null; }

  public static int createEntitySetDescription(FlatBufferBuilder builder,
      byte type,
      int packagesOffset) {
    builder.startTable(2);
    EntitySetDescription.addPackages(builder, packagesOffset);
    EntitySetDescription.addType(builder, type);
    return EntitySetDescription.endEntitySetDescription(builder);
  }

  public static void startEntitySetDescription(FlatBufferBuilder builder) { builder.startTable(2); }
  public static void addType(FlatBufferBuilder builder, byte type) { builder.addByte(0, type, 0); }
  public static void addPackages(FlatBufferBuilder builder, int packagesOffset) { builder.addOffset(1, packagesOffset, 0); }
  public static int createPackagesVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startPackagesVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static int endEntitySetDescription(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public EntitySetDescription get(int j) { return get(new EntitySetDescription(), j); }
    public EntitySetDescription get(EntitySetDescription obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

