// automatically generated by the FlatBuffers compiler, do not modify

package dafi.flatbuf;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class EntityPackageDescription extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_25_2_10(); }
  public static EntityPackageDescription getRootAsEntityPackageDescription(ByteBuffer _bb) { return getRootAsEntityPackageDescription(_bb, new EntityPackageDescription()); }
  public static EntityPackageDescription getRootAsEntityPackageDescription(ByteBuffer _bb, EntityPackageDescription obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public EntityPackageDescription __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int pid() { int o = __offset(4); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public dafi.flatbuf.EntitySectionDescription sections(int j) { return sections(new dafi.flatbuf.EntitySectionDescription(), j); }
  public dafi.flatbuf.EntitySectionDescription sections(dafi.flatbuf.EntitySectionDescription obj, int j) { int o = __offset(6); return o != 0 ? obj.__assign(__indirect(__vector(o) + j * 4), bb) : null; }
  public int sectionsLength() { int o = __offset(6); return o != 0 ? __vector_len(o) : 0; }
  public dafi.flatbuf.EntitySectionDescription.Vector sectionsVector() { return sectionsVector(new dafi.flatbuf.EntitySectionDescription.Vector()); }
  public dafi.flatbuf.EntitySectionDescription.Vector sectionsVector(dafi.flatbuf.EntitySectionDescription.Vector obj) { int o = __offset(6); return o != 0 ? obj.__assign(__vector(o), 4, bb) : null; }
  public dafi.flatbuf.URange gids() { return gids(new dafi.flatbuf.URange()); }
  public dafi.flatbuf.URange gids(dafi.flatbuf.URange obj) { int o = __offset(8); return o != 0 ? obj.__assign(__indirect(o + bb_pos), bb) : null; }
  public String label() { int o = __offset(10); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer labelAsByteBuffer() { return __vector_as_bytebuffer(10, 1); }
  public ByteBuffer labelInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 10, 1); }
  public byte headerType() { int o = __offset(12); return o != 0 ? bb.get(o + bb_pos) : 0; }
  public Table header(Table obj) { int o = __offset(14); return o != 0 ? __union(obj, o + bb_pos) : null; }

  public static int createEntityPackageDescription(FlatBufferBuilder builder,
      int pid,
      int sectionsOffset,
      int gidsOffset,
      int labelOffset,
      byte headerType,
      int headerOffset) {
    builder.startTable(6);
    EntityPackageDescription.addHeader(builder, headerOffset);
    EntityPackageDescription.addLabel(builder, labelOffset);
    EntityPackageDescription.addGids(builder, gidsOffset);
    EntityPackageDescription.addSections(builder, sectionsOffset);
    EntityPackageDescription.addPid(builder, pid);
    EntityPackageDescription.addHeaderType(builder, headerType);
    return EntityPackageDescription.endEntityPackageDescription(builder);
  }

  public static void startEntityPackageDescription(FlatBufferBuilder builder) { builder.startTable(6); }
  public static void addPid(FlatBufferBuilder builder, int pid) { builder.addInt(0, pid, 0); }
  public static void addSections(FlatBufferBuilder builder, int sectionsOffset) { builder.addOffset(1, sectionsOffset, 0); }
  public static int createSectionsVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startSectionsVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static void addGids(FlatBufferBuilder builder, int gidsOffset) { builder.addOffset(2, gidsOffset, 0); }
  public static void addLabel(FlatBufferBuilder builder, int labelOffset) { builder.addOffset(3, labelOffset, 0); }
  public static void addHeaderType(FlatBufferBuilder builder, byte headerType) { builder.addByte(4, headerType, 0); }
  public static void addHeader(FlatBufferBuilder builder, int headerOffset) { builder.addOffset(5, headerOffset, 0); }
  public static int endEntityPackageDescription(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public EntityPackageDescription get(int j) { return get(new EntityPackageDescription(), j); }
    public EntityPackageDescription get(EntityPackageDescription obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

