// automatically generated by the FlatBuffers compiler, do not modify

package dafi.flatbuf;

@SuppressWarnings("unused")
public final class EntityPackageHeader {
  private EntityPackageHeader() { }
  public static final byte NONE = 0;
  public static final byte stops = 1;

  public static final String[] names = { "NONE", "stops", };

  public static String name(int e) { return names[e]; }
}

