// automatically generated by the FlatBuffers compiler, do not modify

package dafi.flatbuf;

@SuppressWarnings("unused")
public final class StopAttrib {
  private StopAttrib() { }
  public static final int DESCENDANCY = 0;
  public static final int SHORT_NAME = 1;
  public static final int SECONDARY_NAME = 2;
  public static final int NONE = 255;
}

