// automatically generated by the FlatBuffers compiler, do not modify

package dafi.flatbuf;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class URange extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_25_2_10(); }
  public static URange getRootAsURange(ByteBuffer _bb) { return getRootAsURange(_bb, new URange()); }
  public static URange getRootAsURange(ByteBuffer _bb, URange obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public URange __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public long first() { int o = __offset(4); return o != 0 ? (long)bb.getInt(o + bb_pos) & 0xFFFFFFFFL : 0L; }
  public long limit() { int o = __offset(6); return o != 0 ? (long)bb.getInt(o + bb_pos) & 0xFFFFFFFFL : 0L; }

  public static int createURange(FlatBufferBuilder builder,
      long first,
      long limit) {
    builder.startTable(2);
    URange.addLimit(builder, limit);
    URange.addFirst(builder, first);
    return URange.endURange(builder);
  }

  public static void startURange(FlatBufferBuilder builder) { builder.startTable(2); }
  public static void addFirst(FlatBufferBuilder builder, long first) { builder.addInt(0, (int) first, (int) 0L); }
  public static void addLimit(FlatBufferBuilder builder, long limit) { builder.addInt(1, (int) limit, (int) 0L); }
  public static int endURange(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public URange get(int j) { return get(new URange(), j); }
    public URange get(URange obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

