// automatically generated by the FlatBuffers compiler, do not modify

package dafi.flatbuf;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class ZQuadTree extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_25_2_10(); }
  public static ZQuadTree getRootAsZQuadTree(ByteBuffer _bb) { return getRootAsZQuadTree(_bb, new ZQuadTree()); }
  public static ZQuadTree getRootAsZQuadTree(ByteBuffer _bb, ZQuadTree obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public ZQuadTree __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public long commonAncestor() { int o = __offset(4); return o != 0 ? bb.getLong(o + bb_pos) : 0L; }
  public dafi.flatbuf.ZQuadTreeLeaf leaves(int j) { return leaves(new dafi.flatbuf.ZQuadTreeLeaf(), j); }
  public dafi.flatbuf.ZQuadTreeLeaf leaves(dafi.flatbuf.ZQuadTreeLeaf obj, int j) { int o = __offset(6); return o != 0 ? obj.__assign(__vector(o) + j * 16, bb) : null; }
  public int leavesLength() { int o = __offset(6); return o != 0 ? __vector_len(o) : 0; }
  public dafi.flatbuf.ZQuadTreeLeaf.Vector leavesVector() { return leavesVector(new dafi.flatbuf.ZQuadTreeLeaf.Vector()); }
  public dafi.flatbuf.ZQuadTreeLeaf.Vector leavesVector(dafi.flatbuf.ZQuadTreeLeaf.Vector obj) { int o = __offset(6); return o != 0 ? obj.__assign(__vector(o), 16, bb) : null; }
  public dafi.flatbuf.ZQuadTreeBranch branches(int j) { return branches(new dafi.flatbuf.ZQuadTreeBranch(), j); }
  public dafi.flatbuf.ZQuadTreeBranch branches(dafi.flatbuf.ZQuadTreeBranch obj, int j) { int o = __offset(8); return o != 0 ? obj.__assign(__indirect(__vector(o) + j * 4), bb) : null; }
  public int branchesLength() { int o = __offset(8); return o != 0 ? __vector_len(o) : 0; }
  public dafi.flatbuf.ZQuadTreeBranch.Vector branchesVector() { return branchesVector(new dafi.flatbuf.ZQuadTreeBranch.Vector()); }
  public dafi.flatbuf.ZQuadTreeBranch.Vector branchesVector(dafi.flatbuf.ZQuadTreeBranch.Vector obj) { int o = __offset(8); return o != 0 ? obj.__assign(__vector(o), 4, bb) : null; }

  public static int createZQuadTree(FlatBufferBuilder builder,
      long commonAncestor,
      int leavesOffset,
      int branchesOffset) {
    builder.startTable(3);
    ZQuadTree.addCommonAncestor(builder, commonAncestor);
    ZQuadTree.addBranches(builder, branchesOffset);
    ZQuadTree.addLeaves(builder, leavesOffset);
    return ZQuadTree.endZQuadTree(builder);
  }

  public static void startZQuadTree(FlatBufferBuilder builder) { builder.startTable(3); }
  public static void addCommonAncestor(FlatBufferBuilder builder, long commonAncestor) { builder.addLong(0, commonAncestor, 0L); }
  public static void addLeaves(FlatBufferBuilder builder, int leavesOffset) { builder.addOffset(1, leavesOffset, 0); }
  public static void startLeavesVector(FlatBufferBuilder builder, int numElems) { builder.startVector(16, numElems, 8); }
  public static void addBranches(FlatBufferBuilder builder, int branchesOffset) { builder.addOffset(2, branchesOffset, 0); }
  public static int createBranchesVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startBranchesVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static int endZQuadTree(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public ZQuadTree get(int j) { return get(new ZQuadTree(), j); }
    public ZQuadTree get(ZQuadTree obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

