// automatically generated by the FlatBuffers compiler, do not modify

package dafi.flatbuf;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class ZQuadTreeBranch extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_25_2_10(); }
  public static ZQuadTreeBranch getRootAsZQuadTreeBranch(ByteBuffer _bb) { return getRootAsZQuadTreeBranch(_bb, new ZQuadTreeBranch()); }
  public static ZQuadTreeBranch getRootAsZQuadTreeBranch(ByteBuffer _bb, ZQuadTreeBranch obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public ZQuadTreeBranch __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public byte quarter() { int o = __offset(4); return o != 0 ? bb.get(o + bb_pos) : 0; }
  public dafi.flatbuf.ZQuadTree subtree() { return subtree(new dafi.flatbuf.ZQuadTree()); }
  public dafi.flatbuf.ZQuadTree subtree(dafi.flatbuf.ZQuadTree obj) { int o = __offset(6); return o != 0 ? obj.__assign(__indirect(o + bb_pos), bb) : null; }

  public static int createZQuadTreeBranch(FlatBufferBuilder builder,
      byte quarter,
      int subtreeOffset) {
    builder.startTable(2);
    ZQuadTreeBranch.addSubtree(builder, subtreeOffset);
    ZQuadTreeBranch.addQuarter(builder, quarter);
    return ZQuadTreeBranch.endZQuadTreeBranch(builder);
  }

  public static void startZQuadTreeBranch(FlatBufferBuilder builder) { builder.startTable(2); }
  public static void addQuarter(FlatBufferBuilder builder, byte quarter) { builder.addByte(0, quarter, 0); }
  public static void addSubtree(FlatBufferBuilder builder, int subtreeOffset) { builder.addOffset(1, subtreeOffset, 0); }
  public static int endZQuadTreeBranch(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public ZQuadTreeBranch get(int j) { return get(new ZQuadTreeBranch(), j); }
    public ZQuadTreeBranch get(ZQuadTreeBranch obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

