// automatically generated by the FlatBuffers compiler, do not modify

package dafi.flatbuf;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class ZQuadTreeLeaf extends Struct {
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public ZQuadTreeLeaf __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public long descendancy() { return bb.getLong(bb_pos + 0); }
  public int value() { return bb.getInt(bb_pos + 8); }

  public static int createZQuadTreeLeaf(FlatBufferBuilder builder, long descendancy, int value) {
    builder.prep(8, 16);
    builder.pad(4);
    builder.putInt(value);
    builder.putLong(descendancy);
    return builder.offset();
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public ZQuadTreeLeaf get(int j) { return get(new ZQuadTreeLeaf(), j); }
    public ZQuadTreeLeaf get(ZQuadTreeLeaf obj, int j) {  return obj.__assign(__element(j), bb); }
  }
}

