include "stops.fbs";
include "utils.fbs";

namespace dafi.flatbuf;

enum EntityType: ubyte {
  STOP = 0
}

table EntitySectionDescription {
  path: string (id: 0);
  attrib_mask: int (id: 1);
}

table EntitySetDescription {
  type: EntityType (id: 0);
  packages: [EntityPackageDescription] (id: 1);
}

table StopPackageHeader {
  quad: uint (id: 0);
}

union EntityPackageHeader {
  stops: StopPackageHeader
}

table EntityPackageDescription {
  pid: int (id: 0);
  sections: [EntitySectionDescription] (id: 1);
  gids: IntRange (id: 2);
  label: string (id: 3);
  header: EntityPackageHeader (id: 5);
}

table BundleDescription {
  entity_sets: [EntitySetDescription] (id: 0);
}

table BundleManifest {
  description: BundleDescription (id: 0);
}

union BundleSectionContents {
  manifest: BundleManifest,
  stops: StopsSection
}

table BundleSection {
  contents: BundleSectionContents (id: 1);
}

root_type BundleSection;
file_identifier "CTFS";
