namespace dafi.flatbuf;

table IntRange {
  // The first value included in the interval.
  first: int (id: 0);

  // One past the the last element in this interval. If .first and .limit are
  // equal the interval is empty and their values don't matter. Note that because
  // this is one *past* the end value you can't express the interval that covers
  // all ints.
  limit: int (id: 1);
}

struct ZQuadTreeLeaf {
  descendancy: ulong (id: 0);
  value: int (id: 1);
}

table ZQuadTreeBranch {
  quarter: int8 (id: 0);
  subtree: ZQuadTree (id: 1);
}

table ZQuadTree {
  common_ancestor: ulong (id: 0);
  leaves: [ZQuadTreeLeaf] (id: 1);
  branches: [ZQuadTreeBranch] (id: 2);
}
