/**
 * This file has been automatically generated by the [capnpc-ts utility](https://github.com/jdiaz5513/capnp-ts).
 */
import * as capnp from "capnp-ts";
import { Struct as __S } from 'capnp-ts';
export declare const _capnpFileId: any;
export declare enum Person_PhoneNumber_Type {
    MOBILE = 0,
    HOME = 1,
    WORK = 2
}
export interface Person_PhoneNumber_Shape {
    number?: string;
    type?: Person_PhoneNumber_Type;
}
export interface Person_PhoneNumber_Json {
    number: string;
    type: Person_PhoneNumber_Type;
}
export declare class Person_PhoneNumber extends __S {
    static readonly _capnp: {
        displayName: string;
        id: string;
        size: capnp.ObjectSize;
    };
    getNumber(): string;
    setNumber(value: string): void;
    get number(): string;
    set number(value: string);
    getType(): Person_PhoneNumber_Type;
    setType(value: Person_PhoneNumber_Type): void;
    get type(): Person_PhoneNumber_Type;
    set type(value: Person_PhoneNumber_Type);
    set(value: Person_PhoneNumber_Shape): void;
    get(): Person_PhoneNumber_Json;
    toJSON(): Person_PhoneNumber_Json;
    toString(): string;
}
export declare namespace Person_PhoneNumber {
    type Json = Person_PhoneNumber_Json;
    type Shape = Person_PhoneNumber_Shape;
    export import Type = Person_PhoneNumber_Type;
}
export declare enum Person_Employment_Which {
    UNEMPLOYED = 0,
    EMPLOYER = 1,
    SCHOOL = 2,
    SELF_EMPLOYED = 3
}
export interface Person_Employment_Shape {
    unemployed?: null;
    employer?: string;
    school?: string;
    selfEmployed?: null;
}
export interface Person_Employment_Json {
    unemployed?: null;
    employer?: string;
    school?: string;
    selfEmployed?: null;
}
export declare class Person_Employment extends __S {
    static readonly UNEMPLOYED = Person_Employment_Which.UNEMPLOYED;
    static readonly EMPLOYER = Person_Employment_Which.EMPLOYER;
    static readonly SCHOOL = Person_Employment_Which.SCHOOL;
    static readonly SELF_EMPLOYED = Person_Employment_Which.SELF_EMPLOYED;
    static readonly _capnp: {
        displayName: string;
        id: string;
        size: capnp.ObjectSize;
    };
    isUnemployed(): boolean;
    setUnemployed(): void;
    getEmployer(): string;
    isEmployer(): boolean;
    setEmployer(value: string): void;
    get employer(): string;
    set employer(value: string);
    getSchool(): string;
    isSchool(): boolean;
    setSchool(value: string): void;
    get school(): string;
    set school(value: string);
    isSelfEmployed(): boolean;
    setSelfEmployed(): void;
    set(value: Person_Employment_Shape): void;
    get(): Person_Employment_Json;
    toJSON(): Person_Employment_Json;
    toString(): string;
    which(): Person_Employment_Which;
}
export declare namespace Person_Employment {
    type Json = Person_Employment_Json;
    type Shape = Person_Employment_Shape;
    export import Which = Person_Employment_Which;
}
export interface Person_Shape {
    id?: number;
    name?: string;
    email?: string;
    phones?: readonly Person_PhoneNumber_Shape[];
    employment?: Person_Employment_Shape;
}
export interface Person_Json {
    id: number;
    name: string;
    email: string;
    phones?: Person_PhoneNumber_Json[];
    employment: Person_Employment_Json;
}
export declare class Person extends __S {
    static readonly _capnp: {
        displayName: string;
        id: string;
        size: capnp.ObjectSize;
    };
    static _Phones: capnp.ListCtor<Person_PhoneNumber>;
    getId(): number;
    setId(value: number): void;
    get id(): number;
    set id(value: number);
    getName(): string;
    setName(value: string): void;
    get name(): string;
    set name(value: string);
    getEmail(): string;
    setEmail(value: string): void;
    get email(): string;
    set email(value: string);
    adoptPhones(value: capnp.Orphan<capnp.List<Person_PhoneNumber>>): void;
    disownPhones(): capnp.Orphan<capnp.List<Person_PhoneNumber>>;
    getPhones(): capnp.List<Person_PhoneNumber>;
    hasPhones(): boolean;
    initPhones(length: number): capnp.List<Person_PhoneNumber>;
    setPhones(value: capnp.List<Person_PhoneNumber>): void;
    get phones(): capnp.List<Person_PhoneNumber>;
    set phones(value: capnp.List<Person_PhoneNumber> | readonly Person_PhoneNumber_Shape[]);
    getEmployment(): Person_Employment;
    initEmployment(): Person_Employment;
    get employment(): Person_Employment;
    set employment(value: Person_Employment_Shape);
    set(value: Person_Shape): void;
    get(): Person_Json;
    toJSON(): Person_Json;
    toString(): string;
}
export declare namespace Person {
    export import Employment = Person_Employment;
    type Json = Person_Json;
    export import PhoneNumber = Person_PhoneNumber;
    type Shape = Person_Shape;
}
export interface AddressBook_Shape {
    people?: readonly Person_Shape[];
}
export interface AddressBook_Json {
    people?: Person_Json[];
}
export declare class AddressBook extends __S {
    static readonly _capnp: {
        displayName: string;
        id: string;
        size: capnp.ObjectSize;
    };
    static _People: capnp.ListCtor<Person>;
    adoptPeople(value: capnp.Orphan<capnp.List<Person>>): void;
    disownPeople(): capnp.Orphan<capnp.List<Person>>;
    getPeople(): capnp.List<Person>;
    hasPeople(): boolean;
    initPeople(length: number): capnp.List<Person>;
    setPeople(value: capnp.List<Person>): void;
    get people(): capnp.List<Person>;
    set people(value: capnp.List<Person> | readonly Person_Shape[]);
    set(value: AddressBook_Shape): void;
    get(): AddressBook_Json;
    toJSON(): AddressBook_Json;
    toString(): string;
}
export declare namespace AddressBook {
    type Json = AddressBook_Json;
    type Shape = AddressBook_Shape;
}
